version: '3.7'

services:
   dev-php:
      container_name: rimutec-dev-php
      hostname: dev-php.local
      build:
         context: .
      working_dir: /src
      volumes:
         - ..:/src:cached
      command: >
         bash -c "sleep infinity"
      networks:
         rimutec:

networks:
   rimutec:
